/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    Copyright: typeof import('./src/components/Copyright.vue')['default']
    ExpansionPanel: typeof import('./src/components/side-projects/ExpansionPanel.vue')['default']
    ExperienceCard: typeof import('./src/components/more-experience/ExperienceCard.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    MoreExperience: typeof import('./src/components/MoreExperience.vue')['default']
    SectionTitle: typeof import('./src/components/SectionTitle.vue')['default']
    SideProjects: typeof import('./src/components/SideProjects.vue')['default']
    WorkExperiencie: typeof import('./src/components/WorkExperiencie.vue')['default']
  }
}
